name: Automerge
on:
  pull_request_target:
    types: [opened, synchronize, reopened, review_requested]

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  renovate-automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Approve PR if not already approved
        run: |
          if [ "$(gh pr view "$PR_URL" --json reviewDecision -q .reviewDecision)" != "APPROVED" ]; then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved."
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for Renovate PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
